Half-working code
Update working for customers
Update working correctly for no updates
Fetch working correctly
Delete not working correctly   --> added code here for validating if
delete has received via id only
Need to check: Deleting a non-existing item / deleting an already
deleted item

Trying to delete customer via non-id
------------------------------------------

1) Initially gave this error (before validation checks)
2016-11-09T18:44:13.060Z 82344ce6-a6ac-11e6-9f25-e3f594e09e1a Customer
attributes received {"firstName":"A"}.
2016-11-09T18:44:13.061Z 82344ce6-a6ac-11e6-9f25-e3f594e09e1a Customer
object created {"_firstName":"A","_deleted":false}.
2016-11-09T18:44:13.061Z 82344ce6-a6ac-11e6-9f25-e3f594e09e1a Proceeding
to delete Customer undefined.
2016-11-09T18:44:13.119Z 82344ce6-a6ac-11e6-9f25-e3f594e09e1a Dynamo
failed to fetch data ValidationException: The provided key element does
not match the schema
2016-11-09T18:44:13.121Z 82344ce6-a6ac-11e6-9f25-e3f594e09e1a
ReferenceError: DaoException is not defined

2) After validation checks
returns 400 error for non-id based deletion, else still giving error for
validation needs to be checked

3) Create not working for customers
Validation check need to be added for serialize (for empty items)
Received event: {
"operation": "create",
"email": "a@c.com",
"first_name": "A",
"last_name": "s",
"phone_number": "1231231458"
}
2016-11-09T19:00:47.753Z d3130cf5-a6ae-11e6-bbec-43b8596b37ca Customer
attributes received
{"email":"a@c.com","firstName":"A","lastName":"s","phoneNumber":"1231231458"}.
2016-11-09T19:00:47.753Z d3130cf5-a6ae-11e6-bbec-43b8596b37ca Customer
object created
{"_id":"a@c.com","_firstName":"A","_lastName":"s","_phoneNumber":"1231231458","_deleted":false}.
2016-11-09T19:00:47.753Z d3130cf5-a6ae-11e6-bbec-43b8596b37ca Proceeding
to save Customer
{"_id":"a@c.com","_firstName":"A","_lastName":"s","_phoneNumber":"1231231458","_deleted":false}.
2016-11-09T19:00:47.754Z d3130cf5-a6ae-11e6-bbec-43b8596b37ca Sending
for fetch:{"TableName":"customers","Key":{"id":"a@c.com"}}
2016-11-09T19:00:47.944Z d3130cf5-a6ae-11e6-bbec-43b8596b37ca
Successfully fetched record from dynamo: {}
2016-11-09T19:00:47.962Z d3130cf5-a6ae-11e6-bbec-43b8596b37ca TypeError:
Cannot read property 'id' of undefined
at AddressSerializer.serialize
(/var/task/app/views/address-serializer.js:11:18)
at AddressSao.create (/var/task/app/services/address-sao.js:24:37)
at /var/task/app/services/customer-service.js:102:25
at /var/task/app/services/customer-service.js:311:9
at /var/task/app/services/customer-service.js:249:20
at Response.<anonymous> (/var/task/app/services/dao/dao.js:96:11)